name: 'Auto Assign Action'
description: 'Add team reviewers to pull requests when pull requests are opened.'
inputs:
  github_token:
    description: 'An organization token with `pull_request:write` and `members:read` acccess'
    required: true
  teams:
    description: 'A comma-separated list of team slugs eligible to be assigned as reviewers'
    required: true
runs:
  using: 'node16'
  main: 'src/index.js'
branding:
  icon: 'user-plus'
  color: 'blue'
